Jun 14 18:34:33 sqlhelper.py INFO Database not found! Creating a new one:sqlhelper.pyhola.db
Jun 14 18:34:33 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:34:53 sqlhelper.py INFO Database Found.Connecting to DB:hola.db
Jun 14 18:34:53 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:36:37 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:36:37 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:36:54 sqlhelper.py INFO Database not found! Creating a new one:/Users/cant/VsCode/qradar-thehive-synchola.db
Jun 14 18:36:54 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:37:29 sqlhelper.py INFO Database Found.Connecting to DB:hola.db
Jun 14 18:37:29 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:37:41 sqlhelper.py INFO Database Found.Connecting to DB:hola.db
Jun 14 18:37:41 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:38:19 sqlhelper.py INFO Database Found.Connecting to DB:hola.db
Jun 14 18:38:19 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:38:50 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:38:50 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:40:13 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:40:13 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:40:30 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:40:30 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:41:33 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:41:33 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 18:59:30 sqlhelper.py INFO Database not found! Creating a new one:hola.db
Jun 14 18:59:30 sqlhelper.py INFO Connected to Database:hola.db
Jun 14 19:00:30 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 19:00:30 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:07:29 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:07:29 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:17:49 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:17:49 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:18:03 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:18:03 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:18:03 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 19:19:17 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:19:17 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:19:17 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 19:20:01 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:20:01 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:20:01 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 19:20:34 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:20:34 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:20:34 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 19:22:55 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:22:55 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:22:55 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:52:39 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:52:39 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:52:39 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:55:10 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:55:10 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:55:10 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:55:10 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 19:56:06 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:56:06 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:56:06 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:56:06 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 19:56:27 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:56:27 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:56:27 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:56:27 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 19:59:24 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 19:59:24 sqlhelper.py INFO Connected to Database:test.db
Jun 14 19:59:24 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 19:59:24 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 20:00:45 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:00:45 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:00:45 sqlhelper.py INFO Table found and connected.:testtable
Jun 14 20:00:45 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 20:01:49 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:01:49 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:01:49 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 20:01:49 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named id
Jun 14 20:02:56 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:02:56 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:02:56 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 20:03:34 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:03:34 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:03:34 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 20:03:53 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:03:53 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:03:53 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 20:03:53 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named col2
Jun 14 20:06:22 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:06:22 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:06:22 sqlhelper.py INFO Table does not exist! Creating a new one.:testtable
Jun 14 20:06:22 sqlhelper.py ERROR Could not insert records to table!:testtable-table testtable has no column named col1
Jun 14 20:07:29 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:07:29 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:07:29 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 20:07:29 sqlhelper.py ERROR Could not insert records to table!:testtable-no such table: testtable
Jun 14 20:08:04 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:08:04 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:08:04 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 20:08:04 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:09:53 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:09:53 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:09:53 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 20:10:17 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:10:17 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:10:17 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:10:29 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:10:29 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:10:29 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:13:47 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:13:47 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:13:47 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:13:47 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:16:02 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:16:02 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:16:02 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:16:02 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 20:17:07 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:17:07 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:17:07 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:17:07 sqlhelper.py ERROR Could not insert records to table!:table1-no such column: id
Jun 14 20:17:29 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:17:29 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:17:29 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:18:59 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:18:59 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:18:59 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:18:59 sqlhelper.py ERROR Could not insert records to table!:table1-no such column: id
Jun 14 20:19:33 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:19:33 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:19:33 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:19:33 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:19:44 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:19:44 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:19:44 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:19:44 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:21:02 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:21:02 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:21:02 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:21:02 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:22:27 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:22:27 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:22:27 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:22:27 sqlhelper.py ERROR Could not insert records to table!:table1-1 values for 3 columns
Jun 14 20:23:31 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:23:31 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:23:31 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:23:31 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 20:23:50 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 20:23:50 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:23:50 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 20:24:44 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:24:44 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:24:44 sqlhelper.py INFO Table found and connected.:table1
Jun 14 20:25:14 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:25:14 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:25:14 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 20:26:10 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:26:10 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:26:10 sqlhelper.py ERROR Could not insert records to table!:table1-near "'id'": syntax error
Jun 14 20:26:27 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:26:27 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:26:27 sqlhelper.py ERROR Could not insert records to table!:table1-near "'id'": syntax error
Jun 14 20:57:33 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:57:33 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:57:33 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 20:59:24 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 20:59:24 sqlhelper.py INFO Connected to Database:test.db
Jun 14 20:59:24 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 21:00:35 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:00:35 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:00:35 sqlhelper.py ERROR Could not insert records to table!:table1-tuple index out of range
Jun 14 21:03:33 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:03:33 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:03:51 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:03:51 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:03:51 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:08:42 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:08:42 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:08:42 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:08:42 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:09:01 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:09:01 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:09:01 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:09:01 sqlhelper.py ERROR Could not insert records to table!:table1-UNIQUE constraint failed: table1.id
Jun 14 21:09:07 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:09:07 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:09:07 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:09:07 sqlhelper.py ERROR Could not insert records to table!:table1-UNIQUE constraint failed: table1.id
Jun 14 21:09:58 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:09:58 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:09:58 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:09:58 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:10:45 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:10:45 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:10:45 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:10:45 sqlhelper.py ERROR Could not insert records to table!:table1-UNIQUE constraint failed: table1.id
Jun 14 21:10:57 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:10:57 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:10:57 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:10:57 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:11:34 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:11:34 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:11:34 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:11:34 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:20:29 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:20:29 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:20:29 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:20:29 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:23:37 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:23:37 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:23:37 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:34:06 sqlhelper.py INFO Database not found! Creating a new one:test.db
Jun 14 21:34:06 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:34:06 sqlhelper.py INFO Table does not exist! Creating a new one.:table1
Jun 14 21:34:06 sqlhelper.py INFO New record inserted to table1 successfully.:"1","2","3"
Jun 14 21:34:20 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:34:20 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:34:20 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:36:04 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:36:04 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:36:04 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:36:40 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:36:40 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:36:40 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:38:13 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:38:13 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:38:13 sqlhelper.py INFO Table found and connected.:table1
Jun 14 21:38:26 sqlhelper.py INFO Database Found.Connecting to DB:test.db
Jun 14 21:38:26 sqlhelper.py INFO Connected to Database:test.db
Jun 14 21:38:26 sqlhelper.py INFO Table found and connected.:table1
